### ISSUE TITLE
/tmp is full

### ISSUE THREAD

**Issue by AuroraWright** [hashbang/hashbang#24] opened 2017-03-01 01:51 UTC
Hi, I tried to send this via e-mail but got a delivery failure notification.
I can't seem to compile anything on hashbang right now, as it reports /tmp to be full (verified with df).
Thank you again for your service!

**Comment by RyanSquared** [comment] 2017-03-01 02:15
Just run `rm /tmp/*` and - while it might nuke your tmux sessions - it should clean it up to a reasonable level. It's a per-user mount so it shouldn't effect anyone else.

**Comment by AuroraWright** [comment] 2017-03-01 02:42
ls reports no files being there (even by displaying hidden ones), so this is very weird.
I had only one background process, but killing it made no difference.

**Comment by KellerFuchs** [comment] 2017-03-01 06:01
@AuroraWright Which server are you on?

This is possibly that the underlying filesystem is now full...

**Comment by KellerFuchs** [comment] 2017-03-01 06:04
@AuroraWright I think that must be `sf1` or `da1`, right?

```
 ansible shell_servers -a 'df -h /tmp'
sf1.hashbang.sh | SUCCESS | rc=0 >>
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        20G   20G     0 100% /

to1.hashbang.sh | SUCCESS | rc=0 >>
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        20G  7.3G   12G  39% /

da1.hashbang.sh | SUCCESS | rc=0 >>
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        20G   19G     0 100% /

ny1.hashbang.sh | SUCCESS | rc=0 >>
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        50G   22G   26G  47% /
```

**Comment by daurnimator** [comment] 2017-03-01 06:05
Is /tmp not a tmpfs?

**Comment by KellerFuchs** [comment] 2017-03-01 06:09
@daurnimator No, the `fstab` change will only take effect after servers reboot.

**Comment by daurnimator** [comment] 2017-03-01 06:10
Huh? what change?

**Comment by KellerFuchs** [comment] 2017-03-01 06:11
OK, sssd is the culprit again:
```
 ansible shell_servers -a 'du -sh /var/log/sssd'
da1.hashbang.sh | SUCCESS | rc=0 >> 13G	 /var/log/sssd
to1.hashbang.sh | SUCCESS | rc=0 >> 401M /var/log/sssd
ny1.hashbang.sh | SUCCESS | rc=0 >> 13G	 /var/log/sssd
sf1.hashbang.sh | SUCCESS | rc=0 >> 13G	 /var/log/sssd
```

That should have been fixed by https://github.com/hashbang/shell-etc/pull/149 though...

**Comment by KellerFuchs** [comment] 2017-03-01 06:12
@daurnimator Mail `<20170209163310.GE2@hashbang.sh>` to the team.
I notified that I changed `fstab` on all servers to put `/tmp` in a tmpfs, effective next reboot.

You even answered that mail  :O

**Comment by daurnimator** [comment] 2017-03-01 06:16
Ah right. so what change did you make in the end?
I thought it would be as simple as `systemctl enable --now tmp.mount`

**Comment by KellerFuchs** [comment] 2017-03-01 06:16
@AuroraWright Please confirm the issue is fixed.

@hashbang/administrators I assumed that the issue was caused by not restarting `sssd` after hashbang/shell-etc#149 was deployed, but cannot confirm easily.
I suggest we control that in a couple of hours.

**Comment by KellerFuchs** [comment] 2017-03-01 06:17
@daurnimator I did an equivalent change in `fstab` instead, documented in that mail...
Regardless of the method, it won't be effective before a reboot (there is live data and active mountpoints under `/tmp`)
PS: Also, let's move this to IRC, this doesn't really belong in the issue's thread.

**Comment by KellerFuchs** [comment] 2017-03-01 07:09
OK, this seems to have done the trick:
```
 ansible shell_servers -a 'du -sh /var/log/sssd'
ny1.hashbang.sh | SUCCESS | rc=0 >> 4.0K	/var/log/sssd
da1.hashbang.sh | SUCCESS | rc=0 >> 4.0K	/var/log/sssd
to1.hashbang.sh | SUCCESS | rc=0 >> 4.0K	/var/log/sssd
sf1.hashbang.sh | SUCCESS | rc=0 >> 4.0K	/var/log/sssd

 ansible shell_servers -a 'df -h /tmp'
to1.hashbang.sh | SUCCESS | rc=0 >>
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        20G  6.9G   12G  37% /

da1.hashbang.sh | SUCCESS | rc=0 >>
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        20G  6.7G   13G  36% /

ny1.hashbang.sh | SUCCESS | rc=0 >>
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        50G  9.4G   38G  20% /

sf1.hashbang.sh | SUCCESS | rc=0 >>
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        20G  6.7G   13G  36% /
```

Closing the issue as the issue is remediated permanently, as far as I can tell.

@AuroraWright Sorry it took so long, thanks for reporting the issue and don't hesitate to reopen the issue if you still experience problems or need clarifications.

**Closed as completed by KellerFuchs** 2017-03-01 07:09 UTC
